# Generated by Django 6.1.1 on 2026-09-27 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_key", models.CharField(max_length=255, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("neighborhood", models.CharField(blank=True, max_length=100)),
                (
                    "quadrant",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NW", "NW"),
                            ("NE", "NE"),
                            ("SE", "SE"),
                            ("SW", "SW"),
                            ("N", "N"),
                            ("S", "S"),
                        ],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("geocoded_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("beds", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "baths",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("sqft", models.IntegerField(blank=True, null=True)),
                ("parking_spaces", models.IntegerField(blank=True, null=True)),
                ("has_parking", models.BooleanField(blank=True, null=True)),
                ("has_washer_dryer", models.BooleanField(blank=True, null=True)),
                ("has_ac", models.BooleanField(blank=True, null=True)),
                ("has_outdoor_space", models.BooleanField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("condo", "Condo"),
                            ("townhome", "Townhome"),
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("available", models.CharField(blank=True, max_length=100)),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                (
                    "overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Manual corrections that survive re-scrapes, e.g. {"parking_spaces": 2, "has_ac": true}',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("interested", "Interested"),
                            ("toured", "Toured"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-first_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=30)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_count", models.IntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_changes",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["seen_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("count", models.IntegerField(default=0)),
                ("new_count", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="listings.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("missed_runs", models.IntegerField(default=0)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_listings",
                        to="listings.listing",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_listings",
                        to="listings.source",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="unique_source_external_id",
                    )
                ],
            },
        ),
    ]
