# Generated by Django 6.1.1 on 2026-09-27 17:41

import re

from django.db import migrations, models

# Frozen copy of listings.address.portland_quadrant so this migration never changes behavior.
_QUADRANT_WORDS = {
    "nw": "NW", "northwest": "NW", "ne": "NE", "northeast": "NE",
    "se": "SE", "southeast": "SE", "sw": "SW", "southwest": "SW",
    "n": "N", "north": "N", "s": "S", "south": "S",
}


def _quadrant(street, city):
    if (city or "").strip().lower() != "portland":
        return ""
    match = re.match(r"\s*\d+[a-z]?(?:-\d+[a-z]?)?\s+([a-z.]+)\s", (street or "").lower())
    return _QUADRANT_WORDS.get(match.group(1).replace(".", ""), "") if match else ""


def backfill_quadrants(apps, schema_editor):
    Listing = apps.get_model("listings", "Listing")
    for listing in Listing.objects.all().only("pk", "street", "city", "overrides"):
        quadrant = (listing.overrides or {}).get("quadrant") or _quadrant(listing.street, listing.city)
        if quadrant:
            Listing.objects.filter(pk=listing.pk).update(quadrant=quadrant)


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="quadrant",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NW", "NW"),
                    ("NE", "NE"),
                    ("SE", "SE"),
                    ("SW", "SW"),
                    ("N", "N"),
                    ("S", "S"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.RunPython(backfill_quadrants, migrations.RunPython.noop),
    ]
