# Generated by Django 6.1.1 on 2026-09-28 17:54

from django.db import migrations, models


def mark_described_as_version_1(apps, schema_editor):
    """Listings that already have details were fetched by version-1 parsers; don't re-fetch them
    unless a scraper's details_version is higher."""
    SourceListing = apps.get_model("listings", "SourceListing")
    SourceListing.objects.exclude(listing__description="").update(details_version=1)


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="listed_at",
            field=models.DateField(
                blank=True,
                help_text="When the current rental listing started, per the listing site",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricechange",
            name="event",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="pricechange",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sourcelisting",
            name="details_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(mark_described_as_version_1, migrations.RunPython.noop),
    ]
