# Generated by Django 6.1.1 on 2026-09-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_quadrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="has_parking",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
