# Generated by Django 6.1.1 on 2026-09-29 15:41

import django.db.models.deletion
import django.utils.timezone
from datetime import timedelta

from django.db import migrations, models

TYPE_LABELS = {"condo": "Condo", "townhome": "Townhome", "house": "House", "apartment": "Apartment", "other": "Other",
               "unknown": "Unknown"}


def seed_feed(apps, schema_editor):
    """Start the feed from existing data: price changes already recorded, and listings found after the
    first day (the first day is the initial import, which isn't news)."""
    Listing = apps.get_model("listings", "Listing")
    PriceChange = apps.get_model("listings", "PriceChange")
    FeedEvent = apps.get_model("listings", "FeedEvent")
    SourceListing = apps.get_model("listings", "SourceListing")
    found_on = {}  # listing -> the site it was first found on
    for listing_id, name in SourceListing.objects.order_by("-first_seen_at", "-pk").values_list("listing_id", "source__name"):
        found_on[listing_id] = name
    first = Listing.objects.order_by("first_seen_at").values_list("first_seen_at", flat=True).first()
    if first is None:
        return
    events = []
    for listing in Listing.objects.filter(first_seen_at__gt=first + timedelta(days=1)):
        parts = [f"${listing.price:,}" if listing.price else "price ?", f"{listing.beds} bd"]
        if listing.baths is not None:
            parts.append(f"{listing.baths.normalize():f} ba")
        parts.append(TYPE_LABELS.get(listing.property_type, listing.property_type))
        events.append(FeedEvent(listing=listing, kind="new_listing", summary=" · ".join(parts),
                                source=found_on.get(listing.pk, ""),
                                happened_at=listing.first_seen_at, created_at=listing.first_seen_at))
    previous = {}
    for change in PriceChange.objects.order_by("listing_id", "seen_at", "pk"):
        old = previous.get(change.listing_id)
        if change.event == "Price change" and old is not None and old != change.price:
            summary = f"{change.source + ': ' if change.source else ''}${old:,} → ${change.price:,}"
            events.append(FeedEvent(listing_id=change.listing_id, kind="price_change", summary=summary, source=change.source,
                                    happened_at=change.seen_at, created_at=change.seen_at, old_price=old, new_price=change.price))
        previous[change.listing_id] = change.price
    FeedEvent.objects.bulk_create(events, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_fix_phantom_price_changes"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new_listing", "New listing"),
                            ("price_change", "Price change"),
                            ("off_market", "Off market"),
                            ("back_on_market", "Back on market"),
                            ("new_site", "Listed on another site"),
                            ("details_changed", "Details changed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("happened_at", models.DateTimeField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("summary", models.CharField(max_length=300)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("old_price", models.IntegerField(blank=True, null=True)),
                ("new_price", models.IntegerField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_events",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.RunPython(seed_feed, migrations.RunPython.noop),
    ]
