# Generated by Django 6.1.1 on 2026-09-29 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_feedevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchPriorities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "search priorities",
            },
        ),
        migrations.CreateModel(
            name="TrendReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("auto", "Daily"), ("manual", "Re-run")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=60)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cache_read_tokens", models.IntegerField(default=0)),
                ("cache_write_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("shortlist", models.JSONField(blank=True, default=list)),
                ("picks", models.JSONField(blank=True, default=list)),
                ("market_read", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
