# Generated by Django 6.1.1 on 2026-09-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_trends"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="special_offer",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
