# Generated by Django 6.1.1 on 2026-09-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_special_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_furnished',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
