# Generated by Django 6.1.1 on 2026-09-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_move_status_to_owners_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="status",
        ),
    ]
