# Generated by Django 6.1.1 on 2026-09-30 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_feed_seen_at"),
        ("listings", "0010_remove_listing_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedevent",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_events",
                to="accounts.searchgroup",
            ),
        ),
        migrations.AlterField(
            model_name="feedevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("new_listing", "New listing"),
                    ("price_change", "Price change"),
                    ("off_market", "Off market"),
                    ("back_on_market", "Back on market"),
                    ("new_site", "Listed on another site"),
                    ("details_changed", "Details changed"),
                    ("status", "Status"),
                    ("comment", "Comment"),
                    ("vote", "Vote"),
                ],
                max_length=20,
            ),
        ),
    ]
