# Generated by Django 6.1.1 on 2026-09-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_notes_to_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="notes",
        ),
    ]
