# Generated by Django 6.1.1 on 2026-09-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_owners_default_filters"),
        ("listings", "0015_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpriorities",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priorities",
                to="accounts.searchgroup",
            ),
        ),
        migrations.AddField(
            model_name="trendreport",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trend_reports",
                to="accounts.searchgroup",
            ),
        ),
    ]
