# Generated by Django 6.1.1 on 2026-10-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0019_sql_console"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
