# Generated by Django 6.1.1 on 2026-10-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0020_source_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendreport",
            name="discoveries",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
