# Generated by Django 6.1.1 on 2026-09-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_owners_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="feed_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
