# Generated by Django 6.1.1 on 2026-09-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_feed_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchgroup",
            name="default_filters",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
